config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    resources :pets, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      resources :purchases, only: [ :new, :create ]
    end
    resources :purchases, only: [ :show, :index ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  validates :specie, presence: true
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode if :will_save_change_to_address?
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Aurélie : had the relation to the pets table -> One user can have many pets
  has_many :pets
  has_many :purchases

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode if :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = policy_scope(Pet)
    if params[:query].present?
      @pets = Pet.where("title ILIKE ? OR specie ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
      @pets = Pet.all if @pets.length.zero?
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @pets = Pet.where(specie: @pet.specie)
    @pets = @pets.reject { |element| element.id == @pet.id }
    @username = @pet.user.email.scan(/\A[^@]+/).join
    authorize @pet
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    authorize @pet
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def update
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.update(pet_params)
    redirect_to pets_path(@pet)
  end

  def delete
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.destroy
    redirect_to pets_url, notice: "Pet has been successfully removed"
  end

  private

  def pet_params
    params.require(:pet).permit(:title, :specie, :description, :age, :price, :gender, :address, :photo)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: :show

  def index
    @purchases = Purchase.all
  end

  def show
    authorize(@purchase)
  end

  def new
    @pet = Pet.find(params[:pet_id])
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new
    @pet = Pet.find(params[:pet_id])
    @purchase.pet = @pet
    @purchase.user = current_user
    @purchase.status = true
    authorize(@purchase)
    if @purchase.save
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  def purchase_params
    params.require(:purchase).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsLover</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="content">
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
  </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%# Second banner possibility, css in _home.scss %>

  <div>
    <img id="index-banner" src="https://petmetalart.com.au/wp-content/uploads/2021/12/Mix-Pets-Banner.png" alt="banner">
  </div>

<h3 class="display-8 mb-4 text-center"><strong>Find your new companion</strong></h3>


<div id="homePageSearching">
    <ul class="navbar-nav me-auto d-flex list-group-horizontal justify-content-center">
      <li class="animal-item">
        <%= link_to(controller: 'pets', action: 'index', query: 'dog') do %>
        <%= image_tag "dog3.png", class: "anivatar" %>
        <% end %>
      </li>
      <li class="animal-item">
        <%= link_to(controller: 'pets', action: 'index', query: 'cat') do %>
        <%= image_tag "cat2.png", class: "anivatar" %>
        <% end %>
      </li>
      <li class="animal-item">
        <%= link_to(controller: 'pets', action: 'index', query: 'rabbit') do %>
        <%= image_tag "rabbit3.png", class: "anivatar" %>
        <% end %>
      </li>
      <li class="animal-item">
        <%= link_to(controller: 'pets', action: 'index', query: 'rodent') do %>
        <%= image_tag "rodent2.png", class: "anivatar" %>
        <% end %>
      </li>
      <li class="animal-item">
        <%= link_to(controller: 'pets', action: 'index', query: 'bird') do %>
        <%= image_tag "bird2.png", class: "anivatar" %>
        <% end %>
      </li>
      <li class="animal-item">
        <%= link_to(controller: 'pets', action: 'index', query: 'poultry') do %>
        <%= image_tag "poultry2.png", class: "anivatar" %>
        <% end %>
      </li>
      <li class="animal-item">
        <%= link_to(controller: 'pets', action: 'index', query: 'fish') do %>
        <%= image_tag "fish2.jpg", class: "anivatar" %>
        <% end %>
      </li>
      <li class="animal-item">
         <%= link_to(controller: 'pets', action: 'index', query: 'horse') do %>
        <%= image_tag "horse2.png", class: "anivatar" %>
        <% end %>
      </li>
    </ul>
</div>

app/views/pets/edit.html.erb
<%= simple_form_ for @pet do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :specie %>
  <%= f.text_field :specie %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

app/views/pets/index.html.erb
<div class="container-cards">
  <div class="cards">

  <% @pets.each do |pet| %>
    <%= link_to pet_path(pet) do %>

     <div class="card-trip">
      <%= cl_image_tag pet.photo.key, height: 300, width: 400, crop: :fill %>
        <div class="card-trip-infos">
          <h2><%= pet.title %></h2>
          <h6>€<%= pet.price.round %><h6>
        <p></p>
        </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container">
  <div class="row justify-content-center" >
    <div class="col-lg-3 cream">
      <div class="form cream">
        <h2>Pet information</h2>
        <%= simple_form_for [@pet] do |f| %>
          <%= f.input :title %>
          <%= f.input :specie, collection: [ "Dog", "Cat", "Rabbit", "Rodent", "Horse", "Fish", "Bird", "Poultry"] %>
          <%= f.input :description %>
          <%= f.input :gender, collection: [ "male", "female" ] %>
          <%# <%= f.input :photo, as: :file %>
      </div>
    </div>
    <div class="col-lg-3 cream">
      <div class="form cream">
        <h2 class="transparent">Pet</h2>
          <%= f.input :age %>
          <%= f.input :price %>
          <%= f.input :address %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Insert", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6 img-left">
    </div>
  </div>
</div>

<%# <%= cl_image_tag @pet.photo.key, height: 300, width: 400, crop: :fill %>

app/views/pets/show.html.erb
<div class="main-container">
  <div class="left-container">
    <div class="left-part">
      <div class="selected-image">
        <%= cl_image_tag @pet.photo.key, height: 400, width: 500, crop: :fill, class: "pet-image" %>
      </div>
      <div class="advert-stats">
        <div class="stat">
          <p>Added on <%= @pet.created_at.day %>/<%= @pet.created_at.month %>/<%= @pet.created_at.year %></p>
        </div>
        <div class="stat">
          <% if @pet.gender == "male" %>
            <i class="fa-solid fa-mars"></i>
          <% else %>
            <i class="fa-solid fa-venus"></i>
          <% end %>
        </div>
        <div class="stat">
          <p><%= @pet.age %> month(s) old</p>
        </div>
      </div>
      <div class="pet-description">
        <p><%= @pet.description %></p>
      </div>
    </div>
    <br>
    <br>
    <h2>Related adverts</h2>
    <br>
    <div class="related-adverts">
      <% @pets.each do |pet| %>
        <% pet_path = "/pets/#{pet.id}" %>
        <a href=<%= pet_path %>>
          <div class="card-product">
            <%= cl_image_tag pet.photo.key, height: 400, width: 500, crop: :fill %>
            <div class="card-product-infos">
              <h2><%= pet.title %></h2>
              <p><%= pet.price.round %> €</p>
              <p><%= pet.description %></p>
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
  <div class="right-container">
    <div class="widget">
      <div class="button">
        <p>
          <%= @pet.price.round %> €
        </p>
      </div>
      <div class="">
        <a id="message-button" class="btn btn-gradient show-button" href="#">
          Message
        </a>
      </div>
      <div class="">
        <div class="modal-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <%= button_to "Buy now", pet_purchases_path(@pet), id:"buy-button", class: "btn btn-gradient show-button" %>
        </div>
      </div>
      <div class="user-pet-card">
        <div class="user-information">
          <div class="user-avatar">
            <img src="https://cdn-icons-png.flaticon.com/512/1946/1946429.png" alt="user-picture" height="90px" width="90px">
          <%# if @pet.user.image_url.exist? %>
            <%#= image_tag @pet.user.image_url, height: 90, width: 90, crop: :fill %>
          <%# end %>
          </div>
          <div class="user-details">
            <p><%= @username %></p>
            <p><%= @pet.user.address %></p>
            <p>member since: <%= @pet.user.created_at.year %></p>
          </div>
        </div>
        <%# <div class="buttons-container">
          <div class="">
            <div class="modal-button" data-bs-toggle="modal" data-bs-target="#exampleModal"> %>
              <%#= button_to "Buy now", pet_purchases_path(@pet), class: "btn btn-gradient show-button" %>
            <%# </div>
          </div> %>
          <%# <div class="card-buttons">
            <div>
              <a class="btn btn-gradient show-button-half" href="#">
                Share
              </a>
            </div>
            <div>
              <a class="btn btn-gradient show-button-half" href="#">
                Report
              </a>
            </div>
          </div> %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Congratulations !</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Your payment was successful, your <%= @pet.specie %> is waiting for you in <%= @pet.address %>.</p>
        <p>Thank you !</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/purchases/index.html.erb
<h1>Buy the Pet</h1>

<% @purchases.each do |purchase| %>
  <%=link_to purchase.status, purchase_path(purchase)%>
  <p>
<% purchase.pet.specie %>
</p>
<% end %>

app/views/purchases/new.html.erb
<%= simple_form_for([@pet, @purchase]) do |f| %>
  <%= f.input :status %>
  <%= f.submit %>
<%end%>

app/views/purchases/show.html.erb
<p>
<%= @purchase.pet.specie %>
<%= @purchase.status %></p>
</p>

<%= link_to "Buy the pet", purchases_path%>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <div class="footer-links align-items-center justify-content-center">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>

    <div class="footer-copyright">
      This website is made with <i class="fas fa-heart"></i> by Zero.Hunger Team
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex align-items-end">
      <%= image_tag "https://cdn.pixabay.com/photo/2016/06/28/13/50/cat-1484725_960_720.png" %>
      <h2>PetsLover</h2>
    </div>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Advert", new_pet_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>